
index:
    path: /
    defaults: { _controller: "AppBundle:Default:status" }
    methods: GET

status:
    path: /status
    defaults: { _controller: "AppBundle:Default:status" }
    methods: GET

test:
    path: /test
    defaults: { _controller: "AppBundle:Default:test" }
    methods: GET

check:
    path: /check
    defaults: { _controller: "AppBundle:Default:test" }
    methods: GET

default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST
