user_new:
    path: /user
    defaults: { _controller: "AppBundle:User:create" }
    methods: POST

user_edit:
    path: /user
    defaults: { _controller: "AppBundle:User:update" }
    methods: PATCH

users:
    path: /user
    defaults: { _controller: "AppBundle:User:getAll" }
    methods: GET
