default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST

status:
    path: /status
    defaults: { _controller: "AppBundle:Default:status" }
    methods: GET
