task_new:
    path: /new
    defaults: { _controller: "AppBundle:Task:create" }
    methods: POST

task_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Task:update", id: null }
    methods: PATCH

task_update_status:
    path: /update-status/{id}
    defaults: { _controller: "AppBundle:Task:updateStatus", id: null }
    methods: PATCH

task_list:
    path: /list
    defaults: { _controller: "AppBundle:Task:getAll" }
    methods: GET

task_detail:
    path: /detail/{id}
    defaults: { _controller: "AppBundle:Task:getOne", id: null }
    methods: GET

task_search:
    path: /search/{search}
    defaults: { _controller: "AppBundle:Task:search", search: null }
    methods: POST

task_remove:
    path: /remove/{id}
    defaults: { _controller: "AppBundle:Task:delete", id: null }
    methods: DELETE
