app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
